# version: '3'
# services:
#   mongodb:
#     image: mongo:6.0
#     container_name: mongodb
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: admin
#       MONGO_INITDB_ROOT_PASSWORD: admin
#     volumes:
#       - mongodb_data:/data/db

#   app:
#     build: .
#     container_name: my-app
#     ports:
#       - "3001:3000"
#     depends_on:
#       - mongodb
#     environment:
#       DATABASE_URL: mongodb://admin:12345@mongodb:27017/mydatabase?authSource=admin
#     volumes:
#       - ./uploads:/app/uploads

# volumes:
#   mongodb_data:




version: '3'
services:
  talknet-backend:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mongodb://admin:12345@db:27017/mydatabase?authSource=admin&directConnection=true'
  db:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345
